// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Pinnacle.ResponsibleGaming.ApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DisableDepositLimit
    {
        /// <summary>
        /// Initializes a new instance of the DisableDepositLimit class.
        /// </summary>
        public DisableDepositLimit() { }

        /// <summary>
        /// Initializes a new instance of the DisableDepositLimit class.
        /// </summary>
        public DisableDepositLimit(string author = default(string), string customerId = default(string))
        {
            Author = author;
            CustomerId = customerId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Author")]
        public string Author { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public string CustomerId { get; set; }

    }
}
