// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Pinnacle.ResponsibleGaming.ApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ModelError
    {
        /// <summary>
        /// Initializes a new instance of the ModelError class.
        /// </summary>
        public ModelError() { }

        /// <summary>
        /// Initializes a new instance of the ModelError class.
        /// </summary>
        public ModelError(object exception = default(object), string errorMessage = default(string))
        {
            Exception = exception;
            ErrorMessage = errorMessage;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Exception")]
        public object Exception { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; private set; }

    }
}
