// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Pinnacle.ResponsibleGaming.ApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ModelState
    {
        /// <summary>
        /// Initializes a new instance of the ModelState class.
        /// </summary>
        public ModelState() { }

        /// <summary>
        /// Initializes a new instance of the ModelState class.
        /// </summary>
        public ModelState(ValueProviderResult value = default(ValueProviderResult), IList<ModelError> errors = default(IList<ModelError>))
        {
            Value = value;
            Errors = errors;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public ValueProviderResult Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Errors")]
        public IList<ModelError> Errors { get; private set; }

    }
}
