// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Pinnacle.ResponsibleGaming.ApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SetDepositLimit
    {
        /// <summary>
        /// Initializes a new instance of the SetDepositLimit class.
        /// </summary>
        public SetDepositLimit() { }

        /// <summary>
        /// Initializes a new instance of the SetDepositLimit class.
        /// </summary>
        public SetDepositLimit(double? amount = default(double?), int? periodInDays = default(int?), DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string author = default(string))
        {
            Amount = amount;
            PeriodInDays = periodInDays;
            StartDate = startDate;
            EndDate = endDate;
            Author = author;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PeriodInDays")]
        public int? PeriodInDays { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Author")]
        public string Author { get; set; }

    }
}
