// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Pinnacle.ResponsibleGaming.ApiClient.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ValidationResponse
    {
        /// <summary>
        /// Initializes a new instance of the ValidationResponse class.
        /// </summary>
        public ValidationResponse() { }

        /// <summary>
        /// Initializes a new instance of the ValidationResponse class.
        /// </summary>
        public ValidationResponse(string message = default(string), IDictionary<string, IList<string>> modelState = default(IDictionary<string, IList<string>>))
        {
            Message = message;
            ModelState = modelState;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ModelState")]
        public IDictionary<string, IList<string>> ModelState { get; set; }

    }
}
